authentication:
  client_id: flask-app
  redirect_uri: http://localhost:5000/oauth2callback
  scopes:
  - openid
  - email
  - profile
  - groups
compliance:
  forbidden_headers:
  - Server
  - X-Powered-By
  required_headers:
  - X-Content-Type-Options
  - X-Frame-Options
  - X-XSS-Protection
  - Strict-Transport-Security
reporting:
  include_recommendations: true
  output_format:
  - json
  - html
  severity_levels:
  - CRITICAL
  - HIGH
  - MEDIUM
  - LOW
  - INFO
security_tests:
  max_retries: 3
  payload_sizes:
  - 1024
  - 10240
  - 102400
  rate_limit_requests: 20
  sql_injection_payloads:
  - ''' OR ''1''=''1'
  - '''; DROP TABLE users; --'
  - 1' UNION SELECT password FROM users--
  timeout: 10
  xss_payloads:
  - <script>alert('XSS')</script>
  - javascript:alert('XSS')
  - <img src=x onerror=alert('XSS')>
targets:
  backend_app: http://localhost:8080
  https_endpoint: https://localhost:5443
  ldap_port: 1389
  oidc_provider: http://localhost:5556
  pep_endpoint: http://localhost:5000
