issuer: http://localhost

storage:
  type: memory

web:
  http: 0.0.0.0:5556

logger:
  level: "debug"
  format: "text"

oauth2:
  skipApprovalScreen: true

staticClients:
- id: flask-app
  redirectURIs:
  - 'http://localhost:5000/oauth2/callback'
  name: 'Flask Application (OAuth2 PEP)'
  secret: flask-app-secret

enablePasswordDB: true

staticPasswords:
- email: "admin@example.com"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466" 